AWSTemplateFormatVersion: 2010-09-09
Description: datalake data domain, dev environment

Parameters:
    pPipelineReference:
        Type: String
        Default: none

Resources:
    rKishu:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: ./foundations-datalake-dev.yaml
            Parameters:
                pPipelineReference: !Ref pPipelineReference
    rEngineering:
        Type: AWS::CloudFormation::Stack
        DependsOn: rKishu
        Properties:
            TemplateURL: ./team-datalake-engineering-dev.yaml
            Parameters:
                pPipelineReference: !Ref pPipelineReference
            Tags:
                - Key: sdlf:team
                  Value: engineering
